module.exports = {
  '/api/*': '/$1',
  '/preregistry/v1': '/preregistryv1',
  '/resources/v2/countries': '/resourcesv2countries',
  '/resources/v2/states': '/resourcesv2states',
  '/resources/v2/states/AC/cities': '/resourcesv2statesACcities',
  '/resources/v2/states/AL/cities': '/resourcesv2statesALcities',
  '/resources/v2/states/SP/cities': '/resourcesv2statesSPcities',
  '/resources/v2/addresses/postal-code/05784050': '/resourcesv2addressespostal-code05784050',
  '/resources/v2/addresses/postal-code/04547090': '/resourcesv2addressespostal-code04547090',
  '/resources/v2/marital-status': '/resourcesv2marital-status',
  '/resources/v2/situations': '/resourcesv2situations',
  '/resources/v2/occupations': '/resourcesv2occupations',
  '/resources/v2/activity-areas': '/resourcesv2activity-areas',
  '/resources/v2/addresses/postal-code/37170000': '/resourcesv2addressespostal-code37170000',
  '/resources/v2/issuing-organs?document=CNH': '/resourcesv2issuing-organsdocumentCNH',
  '/resources/v2/issuing-organs?document=RG': '/resourcesv2issuing-organsdocumentRG',
  '/resources/v2/banks': '/resourcesv2banks',
  '/resources/v2/banks/account-types': '/resourcesv2banksaccount-types',
  '/resources/v2/banks/owner-types': '/resourcesv2banksowner-types',
  '/registry/v3/registry-completion/complete-step': '/registryv3registry-completioncomplete-step',
  '/registry/v3/registry-completion/normalize': '/registryv3registry-completionnormalize',
  '/WebServices/HB/Autenticacao.asmx': '/WebServicesHBAutenticacaoasmx'
}
